
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

const PrivacyPolicy = () => {
    return (
        <main className="bg-background min-h-screen flex flex-col">
            <Navbar />

            <div className="flex-grow pt-32 pb-20 px-6 md:px-12 lg:px-24">
                <div className="max-w-4xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.5 }}
                    >
                        <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-6">Privacy Policy</h1>
                        <p className="text-muted-foreground mb-12 text-lg">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

                        <div className="prose prose-invert max-w-none text-muted-foreground prose-headings:text-foreground prose-a:text-primary hover:prose-a:text-primary/80">
                            <p className="lead text-xl text-foreground mb-8">
                                At Stacli ("we," "our," or "us"), we prioritize the privacy and security of our enterprise clients and their data. This Privacy Policy outlines how we collect, use, process, and protect information when you use our intelligent infrastructure platform, AI agents, and automation services (collectively, the "Services").
                            </p>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">1. Information We Collect</h2>
                            <p className="mb-4">We collect information necessary to provide, secure, and improve our enterprise-grade infrastructure services:</p>
                            <ul className="list-disc pl-6 mb-6 space-y-2">
                                <li><strong>Account Information:</strong> Name, email address, company details, and billing information provided during account creation or contract execution.</li>
                                <li><strong>Operational Data:</strong> Metadata, logs, and performance metrics generated by your use of our automation workflows and AI agents.</li>
                                <li><strong>Usage Data:</strong> Information about how you interact with our platform, including features accessed, time spent, and system configuration settings.</li>
                                <li><strong>Integration Data:</strong> Data from third-party services (ERPs, CRMs, Databases) you explicitly connect to the Stacli platform for orchestration purposes.</li>
                            </ul>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">2. How We Use Your Information</h2>
                            <p className="mb-4">We use the collected data for the following legitimate business purposes:</p>
                            <ul className="list-disc pl-6 mb-6 space-y-2">
                                <li><strong>Service Delivery:</strong> To operate, maintain, and provide the features of the Stacli platform.</li>
                                <li><strong>Optimization:</strong> To analyze performance bottlenecks and optimize automation workflows.</li>
                                <li><strong>Security:</strong> To detect, prevent, and address technical issues, security breaches, and fraudulent activity.</li>
                                <li><strong>Communication:</strong> To send administrative information, including updates, security alerts, and support messages.</li>
                            </ul>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">3. Data Processing & AI Models</h2>
                            <p className="mb-6">
                                Stacli utilizes advanced AI models to power its agents. We adhere to strict data segregation principles. <strong>Your proprietary operational data is not used to train our foundational models</strong> shared across customers unless explicitly authorized in a specific enterprise agreement. Customer-specific fine-tuned models remain isolated to your tenant.
                            </p>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">4. Disclosure of Information</h2>
                            <p className="mb-4">We do not sell your data. We may share information only in the following regulated circumstances:</p>
                            <ul className="list-disc pl-6 mb-6 space-y-2">
                                <li><strong>Service Providers:</strong> With trusted third-party vendors (e.g., cloud hosting provider AWS/Azure) who assist in delivering our services, bound by strict confidentiality agreements.</li>
                                <li><strong>Legal Requirements:</strong> If required by law or in response to valid requests by public authorities (e.g., a court or a government agency).</li>
                                <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets, where user data would be transferred as a business asset.</li>
                            </ul>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">5. Data Security</h2>
                            <p className="mb-6">
                                We implement enterprise-grade security measures designed to protect your data from unauthorized access, alteration, disclosure, or destruction. These include encryption in transit (TLS 1.2+) and at rest (AES-256), strict role-based access controls (RBAC), and regular security audits.
                            </p>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">6. Your Rights</h2>
                            <p className="mb-6">
                                Depending on your jurisdiction (GDPR, CCPA, etc.), you may have rights regarding your personal data, including the right to access, correct, delete, or restrict processing of your data. To exercise these rights, please contact your account manager or our Data Privacy Officer.
                            </p>

                            <h2 className="text-2xl font-bold mt-12 mb-4 text-foreground">7. Contact Us</h2>
                            <p className="mb-6">
                                If you have any questions about this Privacy Policy or our data practices, please contact us at:
                            </p>
                            <div className="bg-card/50 p-6 rounded-lg border border-border">
                                <p className="font-semibold text-foreground">Stacli Privacy Team</p>
                                <p className="mt-2">Email: <a href="mailto:privacy@stacli.com" className="text-primary hover:underline">privacy@stacli.com</a></p>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </div>

            <Footer />
        </main>
    );
};

export default PrivacyPolicy;
